site_name: MousseRoyale
site_description: Security writeups, CTFs, labs, cheatsheets and notes.
site_author: MousseRoyale
site_url: https://mousseroyale.github.io/

theme:
  name: material
  language: en
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

plugins:
  - search
  - awesome-nav
  - tags

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/terminal.js
  - javascripts/clipboard.js
  - javascripts/ctf-filter.js
  - javascripts/title-link.js
  #- javascripts/command-highlight.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

